use log::debug;
use ra_ap_base_db::RootQueryDb;
use ra_ap_hir::{Crate, Semantics};
use ra_ap_ide_db::RootDatabase;
use ra_ap_vfs::Vfs;
use std::path::Path;

/// Collect all crates whose root files are inside the cargo dir.  The target project may have
/// multiple crates, such as a library and a binary.
pub fn find_in_dir(sema: &Semantics<RootDatabase>, vfs: &Vfs, cargo_dir_path: &Path) -> Vec<Crate> {
    let mut crates = Vec::new();
    for db_crate in sema.db.all_crates().iter() {
        let file_id = db_crate.data(sema.db).root_file_id;
        let vfs_path = vfs.file_path(file_id);
        let Some(path) = vfs_path.as_path() else {
            continue;
        };

        // Only consider crates whose root file is inside the provided cargo dir.  We assume other
        // files are from dependencies.  This is not 100% accurate, since the `Cargo.toml` can set
        // `lib.src = "../foo.rs"` and similar, but it should work for the vast majority of
        // projects, including those generated by `c2rust-transpile`.
        let mut ancestors = std::iter::successors(Some(path), |p| p.parent());
        if !ancestors.any(|a| a == cargo_dir_path) {
            debug!("skip {path:?}: outside cargo dir {cargo_dir_path:?}");
            continue;
        }

        debug!("found {path:?}");
        let hir_crate = sema
            .first_crate(file_id)
            .expect("could not find first file in crate");
        crates.push(hir_crate);
    }
    crates
}
