#!/usr/bin/env bash

# Wrap a command that runs `cargo install`
# and clean up intermediate artifacts generated by it.
# The final artifacts in `${CARGO_HOME}/bin` are kept,
# but other intermediate artifacts are deleted so that
# Docker doesn't cache them, as they can be quite large.

set -euox pipefail

export CARGO_TARGET_DIR=/tmp/cargo-target

cleanup() {
    rm -rf "${CARGO_TARGET_DIR}"
    rm -rf "${CARGO_HOME}/registry"
    rm -rf "${CARGO_HOME}/git"
}

trap cleanup EXIT

"${@}"
