name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build-crisp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build tractor-crisp
        run: docker build . -t tractor-crisp

  docker-build-crisp-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build tractor-crisp-user
        run: docker build . -f Dockerfile.work -t tractor-crisp-user

      - uses: astral-sh/setup-uv@v6

      - run: uv sync

      - name: Checkout Test-Corpus
        uses: actions/checkout@v4
        with:
          repository: DARPA-TRACTOR-Program/Test-Corpus
          path: Test-Corpus

      - run: LLM_SAFETY_TRIES=0 ./scripts/test_eval_20250917.py Test-Corpus/Public-Tests/B01_organic/colourblind_lib/

  build-crisp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - run: uv sync

      - run: |
          uv tool install .
          which crisp
